// NatterClient/src/app/components/profile/update-user/update-user.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { CountryResponse } from '../../../models/shared/country-response.model';
import { CountriesService } from '../../../services/shared/countries.service';
import { ProfileService } from '../../../services/profile/profile.service';
import { AuthStore } from '../../../stores/auth.store';
import { initialUpdatePassword, UpdatePasswordModel } from '../../../models/profile/update-password.model';
import { initialProfile, ProfileModel } from '../../../models/profile/profile.model';

@Component({
    selector: 'profile-update-user',
    standalone: true,
    imports: [FormsModule],
    templateUrl: './update-user.component.html'
})

export class UpdateUserComponent implements OnInit {
    // Update Profile - Variables
    userModel = signal<ProfileModel>(initialProfile);
    countries: Array<CountryResponse> = [];
    phoneNumberAreaCodes: Array<string> = [];

    // Update Password - Variables
    passwordModel: UpdatePasswordModel = initialUpdatePassword;

    constructor(private _profileService: ProfileService,
        private _countriesService: CountriesService,
        public authStore: AuthStore)
    {}

    ngOnInit(): void {
        this.getCountries();
        this.getUserDetails();
    }

    // UPDATE PROFILE
    private getUserDetails() {
        try {
            this._profileService.fetchUserDetails()
            .subscribe({
                next: (response) => {
                    if (response.isAuthenticated && response.isSuccess) {
                        this.getAreaCodes(response.profileModel.country);
                        this.userModel.set(response.profileModel);
                    }
                },
                error: (error: HttpErrorResponse) => {
                    console.log(error);
                }
            });
        }
        catch (err) {
            console.log(err);
        }      
    }

    private getCountries() {
        try {
            this._countriesService.getCountries()
            .subscribe({
                next: (response) => {
                    this.countries = this._countriesService.sortByCountryName(response);
                },
                error: (error: HttpErrorResponse) => {
                    console.log("Error", error)
                }
            });
        }
        catch (err) {
            console.log("Exception", err);
        }
    }

    getAreaCodes(selectedCountry?: string) {
        this.userModel().phoneNumberAreaCode = "";

        if (selectedCountry) {
            this.phoneNumberAreaCodes = this._countriesService.getAreaCodesForCountry(this.countries, selectedCountry);
        }
        else {
            this.phoneNumberAreaCodes = this._countriesService.getAreaCodesForCountry(this.countries, this.userModel().country);
        }
    }

    submitChanges() {
        try {
            this._profileService.updateUser(this.userModel())
            .subscribe({
                next: (response) => {
                    if (response.isAuthenticated && response.isSuccess) {
                        this.authStore.setAuth.username = this.userModel().username;
                        console.log("Success", response);
                    }
                },
                error: (error: HttpErrorResponse) => {
                    console.log("Error", error)
                }
            });
        }

        catch (err) {
            console.log("Exception", err);
        }
    }

    // UPDATE PASSWORD
    checkPasswords(): boolean {
        let disableButton: boolean = true;

        if (this.passwordModel.currentPassword !== ""
            && (this.passwordModel.newPassword !== "" && this.passwordModel.confirmPassword !== "")
            && this.passwordModel.newPassword === this.passwordModel.confirmPassword) {

            disableButton = false;
        }

        return disableButton;
    }

    submitNewPassword() {    
        try {
            this._profileService.updatePassword(this.passwordModel)
            .subscribe({
                next: (response) => {
                    if (response.isFailure) {
                        console.log(response.errors);
                    }
                },
                error: (error: HttpErrorResponse) => {
                    console.log("Error", error);
                }
            });
        }

        catch (err) {
            console.log("Exception", err);
        }
    }
}

<div class="form-card">

    <h1 class="text-xl pt-4 flex justify-center">Update Profile</h1>

    <form class="flex flex-col pt-2 px-4 pb-4 gap-4">
        <div class="flex flex-col">
            <label for="emailField">E-Mail</label>
            <div [textContent]="userModel().email"></div>
        </div>

        <div class="flex flex-col">
            <label for="usernameField">Username</label>
            <input type="text" name="username" [(ngModel)]="userModel().username" id="usernameField" class="input" />
        </div>

        <div class="flex flex-col">
            <label>Country</label>
            <select name="country" [(ngModel)]="userModel().country" class="input" (change)="getAreaCodes()">
                <option value="" [selected]='userModel().country === "" ? true : false' disabled>Please select a country
                </option>

                @for (countryInfo of countries; let index = $index; track index) {
                    <option [value]="countryInfo.cca2">
                        {{ countryInfo.flag }} {{ countryInfo.name.common }}
                    </option>
                }
            </select>
        </div>

        <div class="flex flex-col">
            <label>Phone Number</label>
            <div class="flex gap-4">
                <select class="w-32 input text-center" name="phoneNumberAreaCode" [(ngModel)]="userModel().phoneNumberAreaCode">
                    <option value="">Select Code</option>

                    @for(code of phoneNumberAreaCodes; let index = $index; track index) {
                        <option [value]="code">
                            {{ code }}
                        </option>
                    }
                </select>
                <input type="text" pattern="[0-9][+,-, ]" name="phoneNumber" [(ngModel)]="userModel().phoneNumber" class="input w-full"
                    placeholder="Phone Number" />
            </div>
        </div>

        <div class="flex flex-col">
            <label>Password</label>
            <input type="password" name="password" [(ngModel)]="userModel().password" class="input"
                placeholder="Type Your Password to Confirm Changes" />
        </div>

        <div class="flex justify-center">
            <button type="button" (click)="submitChanges()" class="border py-2 px-4" [disabled]="userModel().password === '' ? true : false">
                Update
            </button>
        </div>
    </form>
</div>

<div class="form-card">

    <h1 class="flex justify-center text-xl pt-4">Change Password</h1>

    <form class="flex flex-col gap-4 px-4 pb-4 pt-2">
        <div class="flex flex-col">
            <label>Current Password</label>
            <input type="password" name="current-password" [(ngModel)]="passwordModel.currentPassword" class="input" />
        </div>

        <div class="flex flex-col">
            <label>New Password</label>
            <input type="password" name="new-password" [(ngModel)]="passwordModel.newPassword" class="input" />
        </div>

        <div class="flex flex-col">
            <label>Re-enter New Password</label>
            <input type="password" name="confirm-password" [(ngModel)]="passwordModel.confirmPassword" class="input" />
        </div>

        <div class="flex justify-center">
            <button type="button" (click)="submitNewPassword()" class="px-4 py-2 border"
                [disabled]="checkPasswords()">Update</button>       
        </div>
    </form>
</div>

// NatterClient/src/components/profile/UpdateUser.vue
<template>
    <div class="form-card">
        
        <h1 class="text-xl pt-4 flex justify-center">Update Profile</h1>

        <form @submit.prevent class="flex flex-col pt-2 px-4 pb-4 gap-4">
            <div class="flex flex-col">
                <label for="emailField">E-Mail</label>
                <div v-text="userInfo.email"></div>
            </div>

            <div class="flex flex-col">
                <label for="usernameField">Username</label>
                <input type="text" v-model="userInfo.username" id="usernameField" class="input" />
            </div>

            <div class="flex flex-col">
                <label>Country</label>
                <select v-model="userInfo.country" class="input">
                    <option value="" :selected='userInfo.country === "" ? true : false' disabled>Please select a country</option>
                    <option
                        v-for="countryInfo in countries"
                        :value="countryInfo.cca2"
                        :key="countryInfo.cca2"
                    >
                        {{countryInfo.flag }} {{ countryInfo.name.common }}
                    </option>
                </select>
            </div>

            <div class="flex flex-col">
                <label>Phone Number</label>
                <div class="flex gap-4">
                    <select class="w-32 input text-center" v-model="userInfo.phoneNumberAreaCode">
                        <option value="">Select Code</option>
                        <option
                            v-for="(code, index) in phoneNumberAreaCodes"
                            :value="code"
                            :key="index"
                        >
                            {{ code }}
                        </option>
                    </select>
                    <input type="text" pattern="[0-9][+,-, ]" v-model="userInfo.phoneNumber" class="input w-full" placeholder="Phone Number" />
                </div>
            </div>
            
            <div class="flex flex-col">
                <label>Password</label>
                <input type="password" v-model="password" class="input" placeholder="Type Your Password to Confirm Changes" />
            </div>

            <div class="flex justify-center">
                <button
                    type="button"
                    @click="submitChanges"
                    class="border py-2 px-4"
                    :disabled="password === '' ? true : false"
                >Update</button>
            </div>
        </form>
    </div>
</template>

<script setup>
import { computed, onBeforeMount, reactive, ref } from 'vue';
import { profileUrl } from '@/scripts/apiUrls.js';
import { getCountries, getAreaCodes } from '@/scripts/countryDetails.js';

const props = defineProps({
    userInfo: {
        required: true,
        type: Object
    }
})

// Get details (Name, CCA2, Flag and IDD) of all countries in the world before mount
onBeforeMount(async () => { countries.value = await getCountries() })

// Pass props.UserInfo to a reactive userInfo
const userInfo = reactive(props.userInfo)

const countries = ref([])
const searchCountriesText = ref("")
const phoneNumberAreaCodes = computed(() => { return getAreaCodes(countries.value, userInfo.country) })
const password = ref("")

// Submit function
async function submitChanges()  {
    const body = {
        "email": userInfo.email,
        "username": userInfo.username,
        "password": password.value,
        "phoneNumber": userInfo.phoneNumber,
        "phoneNumberAreaCode": userInfo.phoneNumberAreaCode,
        "country": userInfo.country
    }

    try {
        const response = await fetch(`${profileUrl}/update-user`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(body),
            credentials: "include"
        })
        const data = await response.json()

        if(response.ok) {
            console.log(data)
        }
    }
    catch(error) {
        console.log(error)
    }
}

// Search within countries array for a country name
/* function searchCountries(searchCountriesText) {
    countries.value.forEach(countryInfo => {
        if(countryInfo.name.common.contains(searchCountriesText)) {
            return countryInfo.name.common
        }
    })
} */
</script>
