// NatterClient/src/components/chat/Server.vue
<script setup>
import { ref } from 'vue';

defineProps({
    serverData: {
        type: Object,
        required: false
    }
})

const chatMessage = ref("")

</script>

<template>
    <div class="flex flex-col h-full">
        <section class="flex-grow">
            <div v-text="serverData.name" class="text-center dark:text-light text-dark text-2xl"></div>
        </section>
        <section v-if="serverData.name !== 'Home'">
            <input class="w-full h-8 outline-none p-2 rounded-lg bg-gray-600 text-white" v-model="chatMessage">
        </section>
    </div>
</template>

// NatterClient/src/app/components/chat/server/server.component.ts
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ServerModel } from '../../../models/chat/server.model';

@Component({
    selector: 'chat-server',
    standalone: true,
    imports: [FormsModule],
    templateUrl: './server.component.html'
})

export class ServerComponent {
    @Input({required: true}) serverData: ServerModel = {
        name: "",
        img: ""
    };

    chatMessage: string = "";
}

<div class="flex flex-col h-full">
    <section class="flex-grow">
        <div class="text-center dark:text-light text-dark text-2xl" [textContent]="serverData.name"></div>
    </section>

    @if (serverData.name !== 'Home') {
        <section>
            <input class="w-full h-8 outline-none p-2 rounded-lg bg-gray-600 text-white" [(ngModel)]="chatMessage">
        </section>
    }

</div>
