// NatterClient/src/app/components/chat/sidebar/sidebar.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { MatIcon } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import { ServerModel } from '../../../models/chat/server.model';
import { ThemeSwitcherComponent } from '../../shared/theme-switcher/theme-switcher.component';

@Component({
    selector: 'chat-sidebar',
    standalone: true,
    imports: [RouterLink, MatIcon, ThemeSwitcherComponent],
    templateUrl: './sidebar.component.html'
})

export class SidebarComponent {
    @Input({ required: true }) serversJoined: Array<ServerModel> = [];
    @Input() collapsedSidebar: boolean = true;
    @Output() createServer = new EventEmitter<void>();
    @Output() selectServer = new EventEmitter<string>();
    @Output() collapseSidebar = new EventEmitter<boolean>();

    constructor() {}
}

<div class="flex flex-col gap-y-5 py-3 items-center w-14">
    <a routerLink="/"><img src="/favicon.ico" width="32" /></a>

    <div class="flex items-center justify-center server-icon" title="Home" (click)="selectServer.emit('home')">
        <mat-icon class="text-dark dark:text-light">home</mat-icon>
    </div>

    <div class="flex items-center justify-center server-icon" (click)="createServer.emit()" title="Create Server">
        <mat-icon class="text-dark dark:text-light">add</mat-icon>
    </div>

    <div class="border-t dark:border-light border-dark w-4/5"></div>

    
    @for (server of serversJoined; track server.name) {
        <div class="flex flex-grow items-center justify-center server-icon" (click)="selectServer.emit(server.name)">

            @if (server.img) {
                <img [src]="server.img" width="28" class="p-2" [title]="server.name" />
            }

            @else {
                <mat-icon class="text-dark dark:text-light" [title]="server.name">dns</mat-icon>
            }
        </div>
    }

    <div class="absolute bottom-12 text-dark dark:text-light sm:hidden"
        [title]="collapsedSidebar ? 'Expand Sidebar' : 'Collapse Sidebar'">

        @if (!collapsedSidebar) {
            <mat-icon class="cursor-pointer" (click)="collapseSidebar.emit(true)">chevron_left</mat-icon>
        }

        @else {
            <mat-icon class="cursor-pointer" (click)="collapseSidebar.emit(false)">chevron_right</mat-icon>
        }
    </div>

    <div class="absolute bottom-3 cursor-pointer text-dark dark:text-light">
        <app-theme-switcher />
    </div>
</div>

// NatterClient/src/components/chat/Sidebar.vue
<script setup>
import { RouterLink } from "vue-router";
import ToggleDarkMode from "../navbar/ToggleDarkMode.vue";

defineProps({
  serversJoined: {
    type: Object,
    required: true,
  },
});
</script>

<template>
  <div
    class="fixed top-2 left-2 bottom-2 rounded-2xl flex flex-col gap-5 py-3 items-center w-16 bg-light-soft dark:bg-dark-soft border hover:border-accent border-accent/10 overflow-y-scroll"
  >
    <RouterLink to="/"><img src="/favicon.ico" width="32" /></RouterLink>

    <div
      class="flex items-center justify-center w-10 h-10 bg-light dark:bg-dark hover:bg-accent hover:dark:bg-accent border border-accent rounded-lg hover:rounded-full transition-all duration-200 cursor-pointer"
      title="Home"
      @click="$emit('selectedServer', 'home')"
    >
      <font-awesome-icon
        icon="fa-solid fa-server"
        class="p-2 text-dark dark:text-light"
      ></font-awesome-icon>
    </div>

    <div class="border-t dark:border-light border-dark w-4/5"></div>

    <div v-for="server in serversJoined" :key="server.Name">
      <div
        class="flex flex-grow items-center justify-center w-10 h-10 bg-light dark:bg-dark hover:bg-accent hover:dark:bg-accent border border-accent rounded-lg hover:rounded-full transition-all duration-200 cursor-pointer"
        @click="$emit('selectedServer', server.name)"
      >
        <img
            v-if="server.img"
            :src="server.img"
            width="28"
            class="p-2"
            :title="server.name"
        />
        <font-awesome-icon
            v-else
            icon="fa-solid fa-server"
            class="p-2"
            :title="server.name"
        ></font-awesome-icon>
      </div>
    </div>

    <ToggleDarkMode class="absolute bottom-3" />
    
  </div>
</template>
