// NatterClient/src/components/auth/Login.vue
<template>
    <div class="form-card border border-accent flex flex-col justify-center items-center px-8">

        <h1 class="text-3xl pt-4">Login</h1>

        <div class="py-4">
            <form @submit.prevent class="flex flex-col gap-4">
                <div class="flex flex-col">
                    <label>E-Mail</label>
                    <input type="email"
                        class="input" :class="email === '' ? 'border-red-600' : 'border-green-600'"
                        v-model="email"
                    />
                </div>

                <div class="flex flex-col">
                    <label>Password</label>
                    <input type="password"
                        class="input" :class="password.length <= 8 ? 'border-red-600' : 'border-green-600'"
                        v-model="password"
                    />
                </div>

                <div class="flex justify-center">
                    <button @click="loginAction"
                        :disabled="email === '' || password === '' || password.length <= 8 ? true : false"
                        class="px-4 py-2 border"
                    >
                        Submit
                    </button>
                </div>
                
                <!-- For "errors" object generated when validation error at backend -->
                <div v-if="!userStore.isLoggedIn && received.errors" v-for="(error, index) in received.errors" v-text="error" :key="index"></div>
                
                <!-- For errors returned from backend due to invalid password/email -->
                <div v-else-if="!userStore.isLoggedIn && received.message" v-text="received.message"></div>
            </form>

            <p class="py-4 flex items-center gap-1 cursor-pointer hover:text-accent transition-all duration-150"
                @click="$emit('switchToRegister')"
            >
                Dont have a Natter Account?
                <span class="flex items-center gap-1">
                    Register
                    <ArrowRightIcon class="w-4"/>
                </span>
            </p>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import { useUserStore } from '@/stores/userStore';
import { authUrl } from '@/scripts/apiUrls.js';
import router from '@/router'
import { ArrowRightIcon } from '@heroicons/vue/24/solid'

const userStore = useUserStore()

// Bind variables
const email = ref('')
const password = ref('')

// Received from API
const received = ref(Object)

async function loginAction() {
    const params = {
        "email": email.value,
        "password": password.value
    }

    try {
        const response = await fetch(`${authUrl}/login`, {
            method: "POST",
            credentials: 'include',
            body: JSON.stringify(params),
            headers: {
                "Content-Type": "application/json"
            }
        })
        received.value = await response.json()

        if(response.ok) {
            userStore.getLoginStatus(true)
            userStore.getUsername(received.value.username)
            router.push({name: 'home'})
        }
        else {
            userStore.getLoginStatus(false)
            userStore.getUsername("")
        }
    }
    catch(error) {
        received.value = error
    }
}

</script>

// NatterClient/src/app/components/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../../services/auth/auth.service';
import { LoginModel, LoginStatusModel } from '../../../models/auth/login.model';
import { Router } from '@angular/router';
import { HttpErrorResponse } from '@angular/common/http';
import { AuthStore } from '../../../stores/auth.store';

@Component({
    selector: 'app-login',
    standalone: true,
    imports: [FormsModule],
    templateUrl: './login.component.html',
})
export class LoginComponent {
    title = 'Natter';
    pageTitle = 'Login';

    // Page Variables
    loginModel: LoginModel = {
        email: "",
        password: ""
    }

    received: any = new Object();

    constructor(private _authService: AuthService, private _authStore: AuthStore, private _router: Router) {}

    async loginAction() {
        try {
            this._authService.performLogin(this.loginModel)
            .subscribe(
                (response) => {
                    if (response.isSuccess && response.isAuthenticated) {                    
                        this._authStore.setAuth = response;
                        this._router.navigateByUrl("/");
                        console.log(response);
                    }
                },
                (error: HttpErrorResponse) => {
                    this._authStore.setAuth = error.error;
                }
            );
        }
        catch (exception) {
            console.log(exception);
        }
    }

    public switchToRegister() {
        this._router.navigateByUrl("/register");
    }
}

<div
    class="form-card border border-accent flex flex-col justify-center items-center px-8"
>
    <h1 class="text-3xl pt-4">{{ pageTitle }}</h1>

    <div class="py-4">
        <form class="flex flex-col gap-4">
            <div class="flex flex-col">
                <label>E-Mail</label>
                <input
                    type="email"
                    name="email"
                    [class]="
                        loginModel.email === ''
                            ? 'input border-red-600'
                            : 'input border-green-600'
                    "
                    [(ngModel)]="loginModel.email"
                />
            </div>

            <div class="flex flex-col">
                <label>Password</label>
                <input
                    type="password"
                    name="password"
                    [class]="
                        loginModel.password.length <= 8
                            ? 'input border-red-600'
                            : 'input border-green-600'
                    "
                    [(ngModel)]="loginModel.password"
                />
            </div>

            <div class="flex justify-center">
                <button
                    type="button"
                    [disabled]="loginModel.email === '' || loginModel.password === '' ? true : false"
                    class="px-4 py-2 border"
                    (click)="loginAction()"
                >
                    Submit
                </button>
            </div>

            <!-- For "errors" object generated when validation error at backend -->
            <!-- TODO -->

            <!-- For errors returned from backend due to invalid password/email -->
            <!-- TODO -->
        </form>

        <p
            class="py-4 flex items-center gap-1 cursor-pointer hover:text-accent transition-all duration-150"
            (click)="switchToRegister()"
        >
            Dont have a Natter Account?
            <span class="flex items-center gap-1">
                Register
                <!--ArrowRightIcon class="w-4" /-->
            </span>
        </p>
    </div>
</div>
