// NatterClient/src/components/home/Hero.vue
<script setup>
import { RouterLink } from 'vue-router';

</script>

<template>
    <div class="max-h-screen dark:bg-dark-soft bg-light-soft">
        <div class="container flex flex-1 flex-col items-center justify-center py-40 text-white text-center">
            <h1 class="text-7xl font-palanquin font-extrabold py-5 text-accent">Stay Connected, Anytime, Anywhere!</h1>
            <p class="text-xl font-montserrat font-bold dark:text-light text-dark">Experience the Ultimate Chatting App - Instant Communication, Rich Features, and More!</p>
            <RouterLink :to="{name: 'chats'}"><button class="button-hero-accent">Start Chatting</button></RouterLink>
        </div>
    </div>
</template>

// NatterClient/src/app/components/home/hero/hero.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AuthStore } from '../../../stores/auth.store';

@Component({
    selector: 'app-hero',
    standalone: true,
    imports: [RouterLink],
    templateUrl: './hero.component.html'
})

export class HeroComponent implements OnInit {
    constructor(public authStore: AuthStore) {}

    ngOnInit(): void {}
}

<div class="container flex flex-1 flex-col items-center justify-center pt-40 pb-32 text-white text-center">
    <h1 class="text-7xl font-palanquin font-extrabold py-5 text-accent">
        Stay Connected, Anytime, Anywhere!
    </h1>
    <p class="text-xl font-montserrat font-bold dark:text-light text-dark">
        Experience the Ultimate Chatting App - Instant Communication, Rich
        Features, and More!
    </p>

    @if (!authStore.currentAuthStatus().isAuthenticated) {
        <a routerLink="register">
            <button class="button-hero-accent">Start Chatting</button>
        </a>
    }

    @else {
        <a routerLink="chat">
            <button class="button-hero-accent">Start Chatting</button>
        </a>
    }
</div>
